-- Totals by country

select   COUNTRY_REGION, SUM(CASES) AS Cases
from     ECDC_GLOBAL
group by COUNTRY_REGION;


-- Change over time
select DATE,
       COUNTRY_REGION,
       PROVINCE_STATE,
       SUB_REGION_2,
       GROCERY_AND_PHARMACY_CHANGE_PERC,
       PARKS_CHANGE_PERC,
       RESIDENTIAL_CHANGE_PERC,
       RETAIL_AND_RECREATION_CHANGE_PERC,
       TRANSIT_STATIONS_CHANGE_PERC,
       WORKPLACES_CHANGE_PERC
from   GOOG_GLOBAL_MOBILITY_REPORT
where  COUNTRY_REGION = 'United States'
  and PROVINCE_STATE = 'Indiana'
  AND SUB_REGION_2 like 'Hamilt%';
  
  
-- Cases to fatalities
SELECT m.COUNTRY_REGION, m.DATE, m.CASES, m.DEATHS, m.DEATHS / m.CASES as CFR
FROM (SELECT COUNTRY_REGION, DATE, AVG(CASES) AS CASES, AVG(DEATHS) AS DEATHS
      FROM ECDC_GLOBAL
      GROUP BY COUNTRY_REGION, DATE) m
WHERE m.CASES > 0;
  